export class InvalidPassword extends Error {}
export class UserExists extends Error {}
export class UserNotFound extends Error {}
export class TokenNotFound extends Error {}
export class UserNotActivated extends Error {}
export class AuthenticatorError extends Error {}
export class NotCorrectVerificationCode extends Error {}
export class VerificationIsNotFound extends Error {}
export class CompanyAdminOnly extends Error {}
